local helper = require "penta_assets/asset_helper"

local MODELS = {
  { name = "", uri = "industry/saw_mill/era_a/sm_large_log.mdl" },
  { name = "", uri = "industry/saw_mill/main_building_extension.mdl" },
  { name = "", uri = "industry/saw_mill/main_building_garage.mdl" },
  { name = "", uri = "industry/forest/era_a/axe.mdl" },
  --{ name = "", uri = "industry/forest/era_a/forest_storage_01.mdl" },
  { name = "", uri = "industry/forest/era_a/forest_storage_02.mdl" },
  { name = "", uri = "industry/forest/era_a/forest_wooden_box.mdl" },
  { name = "", uri = "industry/forest/era_a/tree_stump.mdl" },
  { name = "", uri = "industry/forest/stroage.mdl" },
}
local ASSET_CONFIG = {
  category = { "penta_rural_assets" },
  sub_category = "Forestry assets",
  description = "Forestry assets",
  has_icon_button = false,
  has_magnet = false,
  has_track_height = false,
  has_seperated_scales = false
}

-- ================================================================== --

function data()

  return {
    type = "ASSET_DEFAULT",
    description = {
      name = ASSET_CONFIG.sub_category,
      description = ASSET_CONFIG.description,
    },
    availability = {
      yearFrom = 1850,
      yearTo = 0,
    },
    buildMode = "MULTI",
    categories = ASSET_CONFIG.category,
    order = 100,
    skipCollision = true,
    autoRemovable = false,

    params = helper.generateAssetParameters(ASSET_CONFIG, MODELS),

    updateFn = function(params)
      return helper.updateFnAsset(MODELS, params)
    end
  }
end
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bert.
--- DateTime: 11-06-2022 15:23
---
